# this will be a workflow name in GitHub
name: CI/CD

on:
  push:
    branches: ["main"]

# this is for 'Login to Azure' step
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # 'dotnet test' will implicitly trigger 'dotnet build' with the same configuration
      # --configuration Release
      - name: Build and Run Tests
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            # this will be 'app-artifact.zip'
            name: app-artifact
            # this folder and the one from 'Download artifact' step - are different
            # as jobs DO NOT SHARE file system while running
            path: artifacts/

  deploy-dev:
    name: CD (deploy to dev)
    runs-on: ubuntu-latest
    # this will guarantee that 'deploy-dev' job will run AFTER 'build' job
    needs: build
    # with this secrets can be re-used using the same naming as ${{ secrets.AZURE_CLIENT_ID }}
    # but
    # - secrets should be saved as Environment secrets (not Repository ones)
    # Azure federated credentials should use 'Environment' as Entity (NOT BRANCH!!)
    environment: dev

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          # this will be 'app-artifact.zip'
          name: app-artifact
          # this folder and the one from 'Upload artifact' step - are different
          # as jobs DO NOT SHARE file system while running
          path: artifacts/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # these are values from Azure Managed Identity => Settings => Properties
          # saved in GitHub as 'dev' Environment secrets
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy artifact to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          # Azure App Service name
          app-name: app-github-actions-demo-dev
          # this is the folder from Download artifact step
          package: artifacts/