name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: CI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # 'dotnet test' will implicitly trigger 'dotnet build' with the same configuration
      # --configuration Release
      - name: Build and Run Tests
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifact  
        uses: actions/upload-artifact@v4
        with:
            # this will be 'app-artifact.zip'
            name: app-artifact
            path: artifacts/