# 'PR Verify' will be a workflow name in GitHub
name: PR Verify

# workflow trigger
on:
  pull_request:
    branches: ["main"]

# all jobs in one workflow run in parallel by default
# but
# if wee need job 'B' runs after successful job 'A' => add needs: A to job B
jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # 'dotnet build' implicitly calls 'dotnet restore'
      # but it's better to have it as a separate step for debugging dependency issues
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      # 'dotnet test' will discover and run all the tests in the repository
      # '--no-build' will reuse the .dlls from step 'Build with .Net'
      - name: Run Tests
        run: dotnet test --configuration Release --no-build