name: "Step - Deploy"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    name: CD (deploy to ${{ inputs.env }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      # need to get access to the 'infrastructure' folder and Bicep there while running IaC
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          # this will be 'app-artifact.zip'
          name: app-artifact
          # this folder and the one from 'Upload artifact' step - are different
          # as jobs DO NOT SHARE file system while running
          path: artifacts/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # these are values from Azure Managed Identity => Settings => Properties
          # saved in GitHub as 'dev'/'qa' Environment secrets
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run IaC via Bicep (Creat Azure App Service)
        run: |
          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
            --resource-group ${{ inputs.resource_group_name }} \
            --verbose

      - name: Deploy artifact to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          # Azure App Service name
          app-name: app-github-actions-demo-${{ inputs.env }}
          # this is the folder from the 'Download artifact' step
          package: artifacts/